load(
      "@rules_cc//cc:defs.bzl"
   ,  "cc_library"
)

cc_library(
      name       = "aapFunctionalCluster_LogAndTrace"
   ,  srcs       = ["aapFunctionalCluster_LogAndTrace.cpp"]
#  ,  deps       = ["//repo_projects/pProjectFull/main_LATEST/source/SwcServiceEcuM:SwcServiceEcuM"]
   ,  hdrs       = [
            "interface_LogAndTrace.hpp"
         ,  "interface_LogAndTrace_Logger.hpp"
         ,  "interface_LogAndTrace_LogStream.hpp"
      ]
   ,  includes   = ["."]
   ,  visibility = ["//visibility:public"]
)

